---
title: "Численная оптимизация"
date: Tue Feb 21 2017
output:
  html_document:
    md_extensions: +latex_macros
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Без ограничений

`optim(par, fn, gr = NULL, ..., method, control = list())`

Локальный минимум функции `fn`, `par` --- многомерный вектор, начальное приближение.

`gr` --- градиент `fn`; такая же сигнатура, только выдает градиент функции.

Методы:

 * Nelder-Mead ("касательных многогранников").  Локальный экстремум, без градиентов.   Строит касательный симплекс, спускается по ребрам до следующего минимума.  Дополнительные предположения о форме функции.  Медленно сходится.
 * CG
 * BFGS
 * L-BFGS-B: позволяет задать область поиска экстремума в виде многомерного параллелепипеда.  Разрывов быть не должно.  Параллелепипед может быть и бесконечным.
 * SANN ("отжига"): глобальный экстремум.  Оч. медленная скорость сходимости.  Аналог случайного поиска.
 * Brent: вариант золотого сечения для поиска на интервале.

Предположение: В окрестности точки приближения точка принимает конечные значения.  Функция задана на всём $\mathbb{R}^d$.  Если хотим оптиизировать на кусочке --- ограничение: если вышли за область, то $+\infty$.  Однако так создается искусственный разрыв.

Возвращает (см. `?optim`: Value)

## С ограничениями

Если экстремум находится внутри области, то можно ограничения и не использовать --- алгоритм и так сойдется.

Пусть есть индикатор области $D$. Найдем функцию $g(x)$: вне $D$: $g(x) = \infty$, непрерывна: $g(x) \to \infty, x \to \partial D$, внутри области ограничена: $g(x) \leq c < \infty \forall x \in D$.

Другая идея: метод **барьерных функций**. Расссмотрим $h_\gamma(x) = f(x) + \gamma g(x)$.  Устроим итеративную процедуру: найдем $x_1$, $\gamma \leftarrow \gamma / 2$ и т.д.  Есть хорошие шансы, что $x_i \to \arg \min f$.  Если $\gamma \to 0$ слишком быстро, то можем не попасть в область притяжения экстремума.  Если слишком медленно, то медленная скорость сходимости.

В R реализован специальный случай этого: поиск $f(x) \to \min$ с учетом линейных ограничений: $Ax \geq b$.  В качестве барьера, оказыается. можно взять $log(|Ax - b)$.  Функция `constrOptim` (обертка над `optim`) с сигнатурой `constrOptim(theta, fn, ui, ci, ..., control())`, где `ui` --- матрица: `ui %*% theta - ci >= 0`.

`Package View: optimization`